# Generated by Django 2.0.3 on 2018-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_2',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
